### ISSUE TITLE
Chromium and Chrome Canary support

### ISSUE THREAD

**Issue by chris-l** [sindresorhus/kill-tabs#1]
I'm using Chromium 43.0.2357.134 (64-bit).
You need more info for debugging?

In the meantime, this line does the trick for me:

``` bash
ps ax|sed -n -e '/chromium.*--type=renderer/ {/--extension-process/ !{s/^\([0-9]*\).*/\1/p}}'|xargs kill
```

**Comment by sindresorhus** [comment]
This is for Chrome. Chromium is not Chrome. I'll consider adding a flag for Chromium and Chrome Canary.

PR welcome :)

**Comment by chris-l** [comment]
Oh, it makes sense.
