### ISSUE TITLE
Kills all extensions as well as tabs

### ISSUE THREAD

**Issue by DJTB** [sindresorhus/kill-tabs#11]
_Ubuntu running Chrome 51.0.2704.63 (64-bit)_ 
The past few days I've noticed this is killing all my extensions as well as tabs.

![image](https://cloud.githubusercontent.com/assets/5353151/15673484/4ab837e6-277a-11e6-9cf8-19e2837d5691.png)

Haven't used kill-tabs for a week or two - so I presume this has happened with the most recent Chrome (stable) update.

Curious if anyone else has experienced the same issue.

**Comment by kevva** [comment]
This could possibly have changed name https://github.com/sindresorhus/kill-tabs/blob/master/index.js#L30.

**Comment by DJTB** [comment]
Fresh Chrome instance, with 10+ extensions running (while typing this answer)
`pgrep -c 'chrome'`
26  
`pgrep -a 'chrome' | grep -c '\-\-type=renderer'`
21  
`pgrep -a 'chrome' | grep -c '\-\-extension'`
0  
`pgrep -a 'chrome' | grep 'process'`
The only hits are `--type=gpu-process`

**Comment by DJTB** [comment]
_Ubuntu running Chrome 53.0.2785.116 (64-bit)_
I haven't used kill-tabs since June - but just tried it now and everything worked as expected. All tabs were killed, yet all extensions continued running.

`pgrep -a 'chrome' | grep -c '\-\-extension'` is now properly reporting `16` rather than `0` when the script was misbehaving.

Possibly only temporarily affected around Chrome 51

**Comment by fregante** [comment]
Does this happen on Ubuntu only? It hasn't happened for me on macOS 10.13 (Chrome 65)

**Comment by DJTB** [comment]
Well it's now ~18 months later, Chrome 65 is working fine for me on Ubuntu too.
May as well close this for now.
