### ISSUE TITLE
Thank you for this extension!

### ISSUE THREAD

**Issue by dandv** [sindresorhus/kill-tabs#12]
![image](https://cloud.githubusercontent.com/assets/33569/19500764/18c8872e-9555-11e6-9599-dfab7ed90140.png)

(feel free to use the image above as a screenshot; it's the result of killing ~100 tabs).

BTW, tab titles are still preserved, and you can look up any closed tab with the [Tabs extension](https://chrome.google.com/webstore/detail/tabs/cdbepibloojgbmnofbejfgglmdlifadj).

**Comment by sindresorhus** [comment]
Glad you found it useful. I've added your screenshot to the readme :)
