### ISSUE TITLE
Error: spawn wmic ENOENT

### ISSUE THREAD

**Issue by mambax7** [sindresorhus/kill-tabs#3]
On Windows 8.1 I am getting:
spawn wmic ENOENT

I've tried on both stable Chrome, and on Canary.

The command:
kill-tabs --help
works fine.

**Comment by mambax7** [comment]
Command failed: C:\Windows\system32\cmd.exe /s /c "wmic process where Caption='chrome.exe' get CommandLine,ProcessId /format:csv"
'wmic' is not recognized as an internal or external command, operable program or batch file.

**Comment by sindresorhus** [comment]
Then I don't know. It works fine for me on Windows 8.1 with latest Node and cmd.exe. Maybe try upgrading to latest Node if you haven't already.

**Comment by mambax7** [comment]
The issue was that my path didn't work on C:\WINDOWS\System32\wbem where the"wmic" was located.
Once this was fixed, I ran into next problem: 
stdout maxBuffer exceeded.

I found a solution to increase the buffer by adding {maxBuffer: 1024 \* 500} (http://goo.gl/qmONsR) After I added it to win.js:

```
childProcess.exec(cmd,  {maxBuffer: 1024 * 500}, function (err, stdout) {
```

it was working fine.

Thanks for developing this solution - it's definitely very handy, as I am running out of memory very often! :)

**Comment by sindresorhus** [comment]
> The issue was that my path didn't work on C:\WINDOWS\System32\wbem where the"wmic" was located.

Can you elaborate on this?

> I found a solution to increase the buffer by adding {maxBuffer: 1024 \* 500} (http://goo.gl/qmONsR) After I added it to win.js:

That I can fix for you. Try out the latest version: `npm i -g kill-tabs`.

**Comment by mambax7** [comment]
1) wmic is located in:
a) C:\WINDOWS\System32\wbem
b) C:\WINDOWS\SysWOW64\wbem

my PATH didn't include them, so I to test it, I've changed to both folders

I have Windows 8.1 64 bit, so my node.js is also 64 bit.

With your new version, it works fine on: 
    C:\WINDOWS\SysWOW64\wbem>kill-tabs

but on 32 bit I get this error: 
    C:\WINDOWS\System32\wbem>kill-tabs
    spawn taskkill ENOENT

Does it help?

**Comment by mambax7** [comment]
One more thing - you might provide a link to this Chrome extension to reload all tabs on a given page:
https://chrome.google.com/webstore/detail/reload-all-tabs/lgpdljdpanfecnpindkbnikegohoobci
I find it useful if I want to kill, e.g.  all 6 pages, but then reload all tabs on one of the 6 pages. Reloading one tab at a time takes too much time :)

**Comment by sindresorhus** [comment]
> Does it help?

It does make the issue clearer. So thanks. But still no idea how to fix it. Might be an issue with just your system. Or maybe some problem with 64/32-bit thing.

> you might provide a link to this Chrome extension to reload all tabs on a given page:

https://github.com/sindresorhus/kill-tabs/commit/922cb52b1ddb49ba8acb866b388e576aeb82689f

**Comment by einkal** [comment]
Its an issue on my system too.. How can I fix this?? I am working with node 8 and angular 4.. using electron..

**Comment by shubham52520** [comment]
- To enable the proper functioning of the `wmic` command on a Windows-based system.
- You can achieve it by simply including the `C:\WINDOWS\system32\wbem` path in your system's environment variables under the `PATH` setting. 
- After making this adjustment, restart your terminal, and the `wmic` command will operate without issues.
