### ISSUE TITLE
the great suspender

### ISSUE THREAD

**Issue by ear** [sindresorhus/kill-tabs#5]
This is not really an issue, just a mention.

I have the same tendency to open a lot of tabs and in need of a solution to the resource hogging problem. Some time ago I have found this extension called [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg/) [(github repo)](https://github.com/deanoemcke/thegreatsuspender) and have been using it to great satisfaction.

One particular advantage over `kill-tabs` is that you don't have to kill all tabs at once. The granularity provided by the toolbar button is to either kill the current tab or all the tabs in the current window.

Hope it helps!

**Comment by sindresorhus** [comment]
I'm aware of it. I just prefer to be able to kill all the tabs at once. Different needs and usage patterns I guess.
